[package]
org = "madusanka"
name = "json_rpc"
version = "0.1.0"
export=["json_rpc.server", "json_rpc.types", "json_rpc.client"]
authors = ["Madusanka"]
keywords = ["json_rpc"]
repository = "https://github.com/madusankanipunajith/Ballerina-JSON-RPC"
distribution = "2201.0.0"
